
package pecl3.screens;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author mr.blissfulgrin
 */
public class VBackGroundPanel extends javax.swing.JPanel
{
    private final ImageIcon img;
    
    public VBackGroundPanel(int width, int height, String source, int x, int y)
    {
        initComponents();
        this.setSize(width,height);
        this.setLocation(x, y);
        this.img = new ImageIcon("./src/img/"+source+".png");
    }
    
    @Override
    public void paintComponent (Graphics g)
    {  
        g.drawImage(img.getImage(), 0, 0,this.getSize().width,this.getSize().height, null);
        setOpaque(false);
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
