
package pecl3.screens;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;


/**
 *
 * @author mr.blissfulgrin
 */
public class VCarBuffer  extends VBackGroundPanel
{
    private HashMap <Integer,VCar> parking;
    private Boolean fila;
    
    public VCarBuffer(int x, int y)
    {
        super(1140,110,"VOID",x,y);
        initComponents();
        this.parking = new HashMap <>();
        fila = true;
    }
    
    public void newCar(int id)
    {
        VCar car = new VCar((this.getWidth())-VCar.getW()*(parking.size()/2+1),(fila)? 0:50);
        car.newCar(id);
        parking.put(id, car);
        this.add(car);
        fila = !fila;
        this.repaint();
    }
    
    public void reset ()
    {
        parking.clear();
        fila = true;
        this.removeAll();
        this.repaint();
    }
    
    public void removeCar (int id)
    {
        if (parking.containsKey(id))
        {
            VCar car = parking.get(id);
            parking.remove(id);
            car.setVisible(false);
            this.remove(car);

            parking.values().forEach((c) ->
            {
                c.setVisible(false);
                this.remove(c);
                this.repaint();
            });

            ArrayList <Integer> keys = new ArrayList<>();
            parking.keySet().forEach((i) ->
            {
                keys.add(i);
            });
            Collections.sort(keys);
            parking = new HashMap<>();
            fila = true;
            keys.forEach((key) ->
            {
                newCar(key);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
