
package pecl3.screens;

import pecl3.src.conectivity.ClientConection;

/**
 *
 * @author mr.blissfulgrin
 */
public class VClientMenu extends javax.swing.JFrame
{
    private final ClientConection clientConection;
            
    public VClientMenu(ClientConection clientConection)
    {
        initComponents();
        this.clientConection = clientConection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        vSimulation = new javax.swing.JButton();
        sSimulation = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        vSimulation.setBackground(new java.awt.Color(0, 0, 0));
        vSimulation.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        vSimulation.setForeground(new java.awt.Color(0, 153, 204));
        vSimulation.setText("VISUAL SIMULATION");
        vSimulation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vSimulationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 9, 3, 9);
        jPanel2.add(vSimulation, gridBagConstraints);

        sSimulation.setBackground(new java.awt.Color(0, 0, 0));
        sSimulation.setFont(new java.awt.Font("Phosphate", 0, 36)); // NOI18N
        sSimulation.setForeground(new java.awt.Color(102, 255, 255));
        sSimulation.setText("SIMPLE SIMULATION");
        sSimulation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sSimulationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 6, 0, 6);
        jPanel2.add(sSimulation, gridBagConstraints);

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 0, 0));
        salir.setText("EXIT");
        salir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 329;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 9, 9, 9);
        jPanel2.add(salir, gridBagConstraints);

        jPanel1.add(jPanel2, "card2");

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vSimulationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vSimulationActionPerformed
    {//GEN-HEADEREND:event_vSimulationActionPerformed
        VLoad l = new VLoad();
        l.go("CONECTING...");
        VFuelStationClient v = new VFuelStationClient(clientConection);
        clientConection.setDisplay(v);
        v.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_vSimulationActionPerformed

    private void sSimulationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sSimulationActionPerformed
    {//GEN-HEADEREND:event_sSimulationActionPerformed
        VLoad l = new VLoad();
        l.go("CONECTING...");
        SFuelStationClient s = new SFuelStationClient(clientConection);
        clientConection.setDisplay(s);
        s.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_sSimulationActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salirActionPerformed
    {//GEN-HEADEREND:event_salirActionPerformed
        VLoad l = new VLoad();
        l.go("DESCONECTING...");
        VInicio vInicio = new VInicio();
        vInicio.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sSimulation;
    private javax.swing.JButton salir;
    private javax.swing.JButton vSimulation;
    // End of variables declaration//GEN-END:variables
}
