
package pecl3.screens;

import pecl3.src.conectivity.ClientConection;
import pecl3.src.conectivity.SenderUDPClient;


/**
 *
 * @author mr.blissfulgrin
 */
public class VInicio extends javax.swing.JFrame
{

    private int carNumber;
    private int workerNumber;
    
    public VInicio()
    {
        initComponents();
        carNumber = 200;
        workerNumber = 3;
        car.setValue(carNumber);
        carTxt.setText("Cars: "+ carNumber);
        worker.setText("Workers: "+ workerNumber);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        vSimulation = new javax.swing.JButton();
        log = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        sSimulation = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        car = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        lessWorkers = new javax.swing.JButton();
        worker = new javax.swing.JLabel();
        moreWorkers = new javax.swing.JButton();
        carTxt = new javax.swing.JLabel();
        onLine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FuelStation");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        vSimulation.setBackground(new java.awt.Color(0, 0, 0));
        vSimulation.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        vSimulation.setForeground(new java.awt.Color(0, 153, 204));
        vSimulation.setText("VISUAL SIMULATION");
        vSimulation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vSimulationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(vSimulation, gridBagConstraints);

        log.setBackground(new java.awt.Color(0, 0, 0));
        log.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        log.setForeground(new java.awt.Color(0, 153, 51));
        log.setText("VIEW LAST LOG");
        log.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                logActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(log, gridBagConstraints);

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setFont(new java.awt.Font("Phosphate", 1, 48)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 0, 0));
        salir.setText("EXIT");
        salir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(salir, gridBagConstraints);

        sSimulation.setBackground(new java.awt.Color(0, 0, 0));
        sSimulation.setFont(new java.awt.Font("Phosphate", 0, 36)); // NOI18N
        sSimulation.setForeground(new java.awt.Color(102, 255, 255));
        sSimulation.setText("SIMPLE SIMULATION");
        sSimulation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sSimulationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(sSimulation, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        car.setMaximum(1000);
        car.setMinimum(50);
        car.setPaintLabels(true);
        car.setValue(200);
        car.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                carStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 8);
        jPanel1.add(car, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lessWorkers.setText("-");
        lessWorkers.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lessWorkersActionPerformed(evt);
            }
        });
        jPanel2.add(lessWorkers, new java.awt.GridBagConstraints());

        worker.setText("3");
        jPanel2.add(worker, new java.awt.GridBagConstraints());

        moreWorkers.setText("+");
        moreWorkers.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                moreWorkersActionPerformed(evt);
            }
        });
        jPanel2.add(moreWorkers, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        carTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carTxt.setText("Cars");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(carTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        onLine.setBackground(new java.awt.Color(0, 0, 0));
        onLine.setFont(new java.awt.Font("Phosphate", 0, 48)); // NOI18N
        onLine.setForeground(new java.awt.Color(255, 153, 0));
        onLine.setText("OnLine");
        onLine.setMaximumSize(new java.awt.Dimension(374, 67));
        onLine.setMinimumSize(new java.awt.Dimension(374, 67));
        onLine.setPreferredSize(new java.awt.Dimension(374, 67));
        onLine.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onLineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(onLine, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription("FuelStation");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salirActionPerformed
    {//GEN-HEADEREND:event_salirActionPerformed
        VLoad l = new VLoad();
        l.go("EXITING...");
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_logActionPerformed
    {//GEN-HEADEREND:event_logActionPerformed
       VLoad l = new VLoad();
        l.go("LOADING...");
       this.setVisible(false);
       this.dispose();
       new VLog().setVisible(true);
    }//GEN-LAST:event_logActionPerformed

    private void vSimulationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vSimulationActionPerformed
    {//GEN-HEADEREND:event_vSimulationActionPerformed
        VLoad l = new VLoad();
        l.go("LOADING...");
        VFuelStation v = new VFuelStation(workerNumber,carNumber);
        this.setVisible(false);
        this.dispose();
        v.setVisible(true);
    }//GEN-LAST:event_vSimulationActionPerformed

    private void sSimulationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sSimulationActionPerformed
    {//GEN-HEADEREND:event_sSimulationActionPerformed
        VLoad l = new VLoad();
        l.go("LOADING...");
        this.setVisible(false);
        this.dispose();
        SFuelStation s = new SFuelStation(workerNumber,carNumber);
        s.setVisible(true);
    }//GEN-LAST:event_sSimulationActionPerformed

    private void lessWorkersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lessWorkersActionPerformed
    {//GEN-HEADEREND:event_lessWorkersActionPerformed
        if (workerNumber > 1)
        {
            workerNumber --;
            worker.setText("Workers: " + workerNumber);
        }
    }//GEN-LAST:event_lessWorkersActionPerformed

    private void moreWorkersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_moreWorkersActionPerformed
    {//GEN-HEADEREND:event_moreWorkersActionPerformed
        if (workerNumber < 6)
        {
            workerNumber ++;
            worker.setText("Workers: " + workerNumber);
        }
    }//GEN-LAST:event_moreWorkersActionPerformed

    private void carStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_carStateChanged
    {//GEN-HEADEREND:event_carStateChanged
        carTxt.setText("Cars: " + car.getValue());
        carNumber = car.getValue();
    }//GEN-LAST:event_carStateChanged

    private void onLineActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLineActionPerformed
    {//GEN-HEADEREND:event_onLineActionPerformed
        VLoad l = new VLoad();
        l.go("AUTO CONECTING...");
        
        SenderUDPClient sender = new SenderUDPClient();
        sender.start();
        try
        {
            sender.join();
        } 
        catch (InterruptedException ex){}

        byte [] IP = sender.getAutoIP();
        ClientConection clientConection = new ClientConection();
        if (!clientConection.conectable(IP))
        {
            VRemoteConection vRemoteConection = new VRemoteConection(clientConection);
            vRemoteConection.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_onLineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider car;
    private javax.swing.JLabel carTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lessWorkers;
    private javax.swing.JButton log;
    private javax.swing.JButton moreWorkers;
    private javax.swing.JButton onLine;
    private javax.swing.JButton sSimulation;
    private javax.swing.JButton salir;
    private javax.swing.JButton vSimulation;
    private javax.swing.JLabel worker;
    // End of variables declaration//GEN-END:variables
}
