
package pecl3.screens;

/**
 *
 * @author mr.blissfulgrin
 */
public class VWorkerBuffer extends VBackGroundPanel
{
    private final int spots [][];
    VWorker [] worker;
            
    public VWorkerBuffer(int x, int y)
    {
        super(300,500,"VOID",x,y);
        initComponents();
        VHouse h = new VHouse ();
        this.add(h);
        
        worker = new VWorker[8];
        spots = new int [6][2];
        int j;
        for (int i = 0; i < spots.length; i++)
        {
            j = (i < spots.length/2)? 0:1;
            spots[i][0] = 10 + 90*i - 270*j;
            spots[i][1] = 260 + 65 * j;
        }
    }
    
    public void newWorker (int number)
    {
        if (number-1 > spots.length)
        {
            System.out.println("ERROR!!! TOO MANY WORKERS, MAX: " + spots.length);
        }
        else
        {
            VWorker w = new VWorker(spots[number-1][0],spots[number-1][1]);
            w.newWorker(number);
            worker[number-1] = w;
            this.add(w);
        }
        this.repaint();
    }
    
    public void reset ()
    {
        for (int x = 1; x <= worker.length; x++)
        {
            removeWorker(x);
        }
        this.removeAll();
        this.repaint();
        VHouse h = new VHouse ();
        this.add(h);
        this.repaint();
    }
    
    public void removeWorker (int number)
    {
        if (worker[number-1] != null)
        {
            worker[number-1].setVisible(false);
            this.remove(worker[number-1]);
            this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
