.PHONY: clean All

All:
	@echo "----------Building project:[ Cpp - Debug ]----------"
	@cd "Cpp" && "$(MAKE)" -f  "Cpp.mk"
clean:
	@echo "----------Cleaning project:[ Cpp - Debug ]----------"
	@cd "Cpp" && "$(MAKE)" -f  "Cpp.mk" clean
