/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pecl2.screens;

import java.net.Socket;
import java.util.concurrent.atomic.AtomicBoolean;
import pecl2.classes.ClientReciver;
import pecl2.classes.ClientSender;

/**
 *
 * @author mr.blissfulgrin
 */
public class PECL2 extends javax.swing.JFrame
{    
    private final ClientSender s;
    private final ClientReciver r;
    private boolean lastClicked;
    private final AtomicBoolean ended;
    
    public PECL2(Socket socket)
    {
        new Load().go("Starting...");
        initComponents();

        String [] producer_id = {"A","B","C","D","E"};
        String [] consumer_id = {"Luis","Juan","Maria"};
        
        producer0Txt.setText("Producer: "+producer_id[0]);
        producer1Txt.setText("Producer: "+producer_id[1]);
        producer2Txt.setText("Producer: "+producer_id[2]);
        producer3Txt.setText("Producer: "+producer_id[3]);
        producer4Txt.setText("Producer: "+producer_id[4]);
        consumer0Txt.setText("Consumer: "+consumer_id[0]);
        consumer1Txt.setText("Consumer: "+consumer_id[1]);
        consumer2Txt.setText("Consumer: "+consumer_id[2]);
        
        producer0Btt.setText("Stop");
        producer1Btt.setText("Stop");
        producer2Btt.setText("Stop");
        producer3Btt.setText("Stop");
        producer4Btt.setText("Stop");
        producerStop.setText("Stop");
        consumerStop.setText("Stop");
        consumer0Btt.setText("Stop");
        consumer1Btt.setText("Stop");
        consumer2Btt.setText("Stop");
        
        s = new ClientSender(socket,this);
        r = new ClientReciver(socket,this);

        lastClicked = true;
        ended = new AtomicBoolean(false);
        
        r.start();
        s.start();
    }
    
    public synchronized void setState (boolean [] data)
    {
        producer0Btt.setSelected(data[0]);
        producer1Btt.setSelected(data[1]);
        producer2Btt.setSelected(data[2]);
        producer3Btt.setSelected(data[3]);
        producer4Btt.setSelected(data[4]);
        consumer0Btt.setSelected(data[5]);
        consumer1Btt.setSelected(data[6]);
        consumer2Btt.setSelected(data[7]);
        producerStop.setSelected(data[8]);
        consumerStop.setSelected(data[9]); 
        if (data[10])
        {
            txt.setText("SIMULATION FINISHD");
        }
    }
    
    public synchronized boolean [] getButtonState ()
    {
        boolean [] state = new boolean [11];
        state [0] = producer0Btt.isSelected();
        state [1] = producer1Btt.isSelected();
        state [2] = producer2Btt.isSelected();
        state [3] = producer3Btt.isSelected();
        state [4] = producer4Btt.isSelected();
        state [5] = consumer0Btt.isSelected();
        state [6] = consumer1Btt.isSelected();
        state [7] = consumer2Btt.isSelected();
        state [8] = producerStop.isSelected();
        state [9] = consumerStop.isSelected();
        state[10] = lastClicked;
        lastClicked = true;
        return state;
    }
    
    public synchronized void end ()
    {
        s.parar();
        r.parar();
        txt.setText("CONNECTION CLOSED");
    }
    
    public synchronized void simulationEND ()
    {
        txt.setText("SIMULATION FINISHD");
        ended.set(true);
    }
    
    public boolean isEnded()
    {
        return ended.get();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        producer0Btt = new javax.swing.JToggleButton();
        producer1Btt = new javax.swing.JToggleButton();
        producer2Btt = new javax.swing.JToggleButton();
        producer3Btt = new javax.swing.JToggleButton();
        producer4Btt = new javax.swing.JToggleButton();
        consumer0Btt = new javax.swing.JToggleButton();
        consumer1Btt = new javax.swing.JToggleButton();
        consumer2Btt = new javax.swing.JToggleButton();
        producerStop = new javax.swing.JToggleButton();
        consumerStop = new javax.swing.JToggleButton();
        producer0Txt = new javax.swing.JLabel();
        producer1Txt = new javax.swing.JLabel();
        producer2Txt = new javax.swing.JLabel();
        producer3Txt = new javax.swing.JLabel();
        producer4Txt = new javax.swing.JLabel();
        consumer0Txt = new javax.swing.JLabel();
        consumer1Txt = new javax.swing.JLabel();
        consumer2Txt = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        producer0Btt.setText("jToggleButton1");
        producer0Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                producer0BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(producer0Btt, gridBagConstraints);

        producer1Btt.setText("jToggleButton2");
        producer1Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                producer1BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(producer1Btt, gridBagConstraints);

        producer2Btt.setText("jToggleButton3");
        producer2Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                producer2BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(producer2Btt, gridBagConstraints);

        producer3Btt.setText("jToggleButton4");
        producer3Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                producer3BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(producer3Btt, gridBagConstraints);

        producer4Btt.setText("jToggleButton5");
        producer4Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                producer4BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 29);
        jPanel2.add(producer4Btt, gridBagConstraints);

        consumer0Btt.setText("jToggleButton6");
        consumer0Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consumer0BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(consumer0Btt, gridBagConstraints);

        consumer1Btt.setText("jToggleButton7");
        consumer1Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consumer1BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(consumer1Btt, gridBagConstraints);

        consumer2Btt.setText("jToggleButton8");
        consumer2Btt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consumer2BttActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 16);
        jPanel2.add(consumer2Btt, gridBagConstraints);

        producerStop.setText("jToggleButton9");
        producerStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                producerStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 22, 13);
        jPanel2.add(producerStop, gridBagConstraints);

        consumerStop.setText("jToggleButton10");
        consumerStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consumerStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 22, 0);
        jPanel2.add(consumerStop, gridBagConstraints);

        producer0Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producer0Txt.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(producer0Txt, gridBagConstraints);

        producer1Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producer1Txt.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(producer1Txt, gridBagConstraints);

        producer2Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producer2Txt.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(producer2Txt, gridBagConstraints);

        producer3Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producer3Txt.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(producer3Txt, gridBagConstraints);

        producer4Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producer4Txt.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 25);
        jPanel2.add(producer4Txt, gridBagConstraints);

        consumer0Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consumer0Txt.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(consumer0Txt, gridBagConstraints);

        consumer1Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consumer1Txt.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(consumer1Txt, gridBagConstraints);

        consumer2Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consumer2Txt.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 12);
        jPanel2.add(consumer2Txt, gridBagConstraints);

        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setText("SIMULATION ON");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 18, 18);
        jPanel2.add(txt, gridBagConstraints);

        jPanel1.add(jPanel2, "card2");

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        end();
        new Load().go("Quiting.."); 
        Generator g = new Generator ();
        g.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void producer0BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_producer0BttActionPerformed
    {//GEN-HEADEREND:event_producer0BttActionPerformed
        s.send();
    }//GEN-LAST:event_producer0BttActionPerformed

    private void producer1BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_producer1BttActionPerformed
    {//GEN-HEADEREND:event_producer1BttActionPerformed
        s.send();
    }//GEN-LAST:event_producer1BttActionPerformed

    private void producer2BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_producer2BttActionPerformed
    {//GEN-HEADEREND:event_producer2BttActionPerformed
        s.send();
    }//GEN-LAST:event_producer2BttActionPerformed

    private void producer3BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_producer3BttActionPerformed
    {//GEN-HEADEREND:event_producer3BttActionPerformed
        s.send();
    }//GEN-LAST:event_producer3BttActionPerformed

    private void producer4BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_producer4BttActionPerformed
    {//GEN-HEADEREND:event_producer4BttActionPerformed
        s.send();
    }//GEN-LAST:event_producer4BttActionPerformed

    private void consumer0BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consumer0BttActionPerformed
    {//GEN-HEADEREND:event_consumer0BttActionPerformed
        s.send();
    }//GEN-LAST:event_consumer0BttActionPerformed

    private void consumer1BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consumer1BttActionPerformed
    {//GEN-HEADEREND:event_consumer1BttActionPerformed
        s.send();
    }//GEN-LAST:event_consumer1BttActionPerformed

    private void consumer2BttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consumer2BttActionPerformed
    {//GEN-HEADEREND:event_consumer2BttActionPerformed
        s.send();
    }//GEN-LAST:event_consumer2BttActionPerformed

    private void producerStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_producerStopActionPerformed
    {//GEN-HEADEREND:event_producerStopActionPerformed
        s.send();
        lastClicked = false;
    }//GEN-LAST:event_producerStopActionPerformed

    private void consumerStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consumerStopActionPerformed
    {//GEN-HEADEREND:event_consumerStopActionPerformed
        s.send();
        lastClicked = false;
    }//GEN-LAST:event_consumerStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton consumer0Btt;
    private javax.swing.JLabel consumer0Txt;
    private javax.swing.JToggleButton consumer1Btt;
    private javax.swing.JLabel consumer1Txt;
    private javax.swing.JToggleButton consumer2Btt;
    private javax.swing.JLabel consumer2Txt;
    private javax.swing.JToggleButton consumerStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton producer0Btt;
    private javax.swing.JLabel producer0Txt;
    private javax.swing.JToggleButton producer1Btt;
    private javax.swing.JLabel producer1Txt;
    private javax.swing.JToggleButton producer2Btt;
    private javax.swing.JLabel producer2Txt;
    private javax.swing.JToggleButton producer3Btt;
    private javax.swing.JLabel producer3Txt;
    private javax.swing.JToggleButton producer4Btt;
    private javax.swing.JLabel producer4Txt;
    private javax.swing.JToggleButton producerStop;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
