.PHONY: clean All

All:
	@echo "----------Building project:[ Arbol - Debug ]----------"
	@cd "Arbol" && "$(MAKE)" -f  "Arbol.mk"
clean:
	@echo "----------Cleaning project:[ Arbol - Debug ]----------"
	@cd "Arbol" && "$(MAKE)" -f  "Arbol.mk" clean
