.PHONY: clean All

All:
	@echo "----------Building project:[ PEC2 - Debug ]----------"
	@cd "PEC2" && "$(MAKE)" -f  "PEC2.mk"
clean:
	@echo "----------Cleaning project:[ PEC2 - Debug ]----------"
	@cd "PEC2" && "$(MAKE)" -f  "PEC2.mk" clean
