.PHONY: 1
1:
	gcc 1.c -o 1 
	./1

.PHONY: 2
2:
	gcc 2.c -o 2
	./2

.PHONY: 3
3:
	gcc 3y4.c -o 3y4
	./3y4

.PHONY: 4
4:
	gcc 3y4.c -o 3y4
	./3y4

.PHONY: 5
5:
	gcc 5.c -o 5
	./5

.PHONY: 6
6:
	gcc 6y7.c -o 6y7
	./6

.PHONY: 7
7:
	gcc 6y7.c -o 6y7
	./7

.PHONY: 8
8:
	gcc 8.c -o 8
	./8

.PHONY: 9
9:
	gcc 9.c -o 9
	./9

.PHONY: 10
10:
	gcc 10.c -o 10
	./10

.PHONY: 11
11:
	gcc 11.c -o 11
	./11

.PHONY: 12
12:
	gcc 12.c -o 12
	./12

.PHONY: clean
clean:
	rm -f 1 2 3y4 5 6y7 8 9 datos_ej88.txt volcado_ej9.txt 10 11 datos_10.txt resultados_10.txt 12 ej12.txt
