.PHONY: clean All

All:
	@echo "----------Building project:[ COLAS - Debug ]----------"
	@cd "COLAS" && "$(MAKE)" -f  "COLAS.mk"
clean:
	@echo "----------Cleaning project:[ COLAS - Debug ]----------"
	@cd "COLAS" && "$(MAKE)" -f  "COLAS.mk" clean
